# Generated by Django 4.1.7 on 2023-03-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyglottal_project', '0002_wannavisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsFavCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyglottal_project.favcities')),
            ],
        ),
    ]
