# Generated by Django 4.1.7 on 2023-03-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyglottal_project', '0003_commentsfavcities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsFavCities',
        ),
    ]
