# Generated by Django 4.1.7 on 2023-03-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyglottal_project', '0005_commentsfavcities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CommentsFavCities',
        ),
    ]
